# Site settings
title: SPJedi Elevating Expectations
email: info@spjedi.com
description: SP Jedi's provides SharePoint builds, Top-Notch Websites, Operational Improvement, and SharePoint Migration. Office 365 Installation and Migration
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spjedi.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems: ["jekyll-sitemap"]