- title: SharePoint Training can be a hoot
  date: "04.27.2014"
  time: "01:00 EST"
  description: Not all trainings have to be the same. We will be adding one each week after April.
  video: https://www.youtube.com/embed/PYOSKYWg-5E
  document: /documents/Smart_Kitten_Cat_Buyers_Guide_July2013_web.pdf
- title: SharePoint Document Libraries
  date: "05.11.2016"
  time: "1:00PM EST"
  description: Glorified File Shares? Umm No! How to use the SharePoint document repository to create a super-charged shared drive for your documents. During this training we will show some examples of how automated Document Libraries can become in a matter of minutes. Take the first step in collaboration. 