- title: SharePoint Training
  date: "11.04.2014"
  time: "14:45"
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  video: https://www.youtube.com/embed/PYOSKYWg-5E
  document: /documents/Smart_Kitten_Cat_Buyers_Guide_July2013_web.pdf
- header: How to adopt a cat
  date: "23.04.2016"
  time: "09:30"
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
- header: SharePoint Online
  date: "03.12.2016"
  time: "10:00"
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.