- title: SharePoint Training
  date: "11.22.2014"
  time: "14:45"
  description: If you want to learn about owls this is the place. It's a hoot, but I assure you the rest will be about SharePoint and Microsoft Products.
  video: https://www.youtube.com/embed/PYOSKYWg-5E
  document: /documents/Smart_Kitten_Cat_Buyers_Guide_July2013_web.pdf
- header: How to adopt a cat
  date: "03.04.2016"
  time: "09:30"
  description: Document libraries, they are way more powerful than you think. The ins and outs of how to make them better.
- header: SharePoint Online
  date: "03.12.2016"
  time: "10:00"
  description: Automating Processes is way easier than you will even believe. We will show you some quick tips to give you more time back in your day.